url: https://petrashevich.github.io
baseurl: ""

# Site settings
title: Brainfy
emails: 
  - info@brainfy.pl
  - a.misiak@brainfy.pl
  - i.petrashevich@brainfy.pl
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Aliaksei Misiak
  pic: 1
  position: 
  social:

- name: Ilya Petrashevich
  pic: 2
  position: 
  social:
   

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: linkedin
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: youtube 
    url: http://bitbucket.org/jekyll


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
